structure(list(url = "https://api.github.com/repos/pedrocoutinhosilva/hexFinder/git/trees/fake?recursive=1", 
    status_code = 404L, headers = structure(list(server = "GitHub.com", 
        date = "Wed, 25 Jan 2023 20:38:11 GMT", `content-type` = "application/json; charset=utf-8", 
        `x-github-media-type` = "github.v3", `x-github-api-version-selected` = "2022-11-28", 
        `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
        `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
        `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `content-security-policy` = "default-src 'none'", vary = "Accept-Encoding, Accept, X-Requested-With", 
        `content-encoding` = "gzip", `x-ratelimit-limit` = "60", 
        `x-ratelimit-remaining` = "47", `x-ratelimit-reset` = "1674682146", 
        `x-ratelimit-resource` = "core", `x-ratelimit-used` = "13", 
        `content-length` = "116", `x-github-request-id` = "B2FA:1776:935EE6:95E3C5:63D19333"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "GitHub.com", date = "Wed, 25 Jan 2023 20:38:11 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `x-github-media-type` = "github.v3", `x-github-api-version-selected` = "2022-11-28", 
            `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
            `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
            `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
            `content-security-policy` = "default-src 'none'", 
            vary = "Accept-Encoding, Accept, X-Requested-With", 
            `content-encoding` = "gzip", `x-ratelimit-limit` = "60", 
            `x-ratelimit-remaining` = "47", `x-ratelimit-reset` = "1674682146", 
            `x-ratelimit-resource` = "core", `x-ratelimit-used` = "13", 
            `content-length` = "116", `x-github-request-id` = "B2FA:1776:935EE6:95E3C5:63D19333"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest/reference/git#get-a-tree\"\n}\n"), 
    date = structure(1674679091, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.6e-05, 
    connect = 3.7e-05, pretransfer = 9e-05, starttransfer = 0.18773, 
    total = 0.187772)), class = "response")
