structure(list(method = "GET", url = "https://api.github.com/repos/pedrocoutinhosilva/hexFinder/git/trees/master?recursive=1", 
    status_code = 404L, headers = structure(list(Server = "GitHub.com", 
        Date = "Thu, 26 Jan 2023 13:42:25 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", `X-OAuth-Scopes` = "admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, repo, user, workflow, write:discussion, write:packages", 
        `X-Accepted-OAuth-Scopes` = "", `X-GitHub-Media-Type` = "github.v3; format=json", 
        `x-github-api-version-selected` = "2022-11-28", `X-RateLimit-Limit` = "5000", 
        `X-RateLimit-Remaining` = "4996", `X-RateLimit-Reset` = "1674743567", 
        `X-RateLimit-Used` = "4", `X-RateLimit-Resource` = "core", 
        `Access-Control-Expose-Headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
        `Access-Control-Allow-Origin` = "*", `Strict-Transport-Security` = "max-age=31536000; includeSubdomains; preload", 
        `X-Frame-Options` = "deny", `X-Content-Type-Options` = "nosniff", 
        `X-XSS-Protection` = "0", `Referrer-Policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `Content-Security-Policy` = "default-src 'none'", Vary = "Accept-Encoding, Accept, X-Requested-With", 
        `Content-Encoding` = "gzip", `X-GitHub-Request-Id` = "B2ED:A7D7:360D899:3705600:63D28341"), class = "httr2_headers"), 
    body = charToRaw("{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest/reference/git#get-a-tree\"\n}\n")), class = "httr2_response")
