structure(list(url = "https://api.github.com/repos/pedrocoutinhosilva/imola/git/trees/main?recursive=1", 
    status_code = 401L, headers = structure(list(server = "GitHub.com", 
        date = "Wed, 25 Jan 2023 20:37:59 GMT", `content-type` = "application/json; charset=utf-8", 
        `content-length` = "90", `x-github-media-type` = "github.v3", 
        `x-ratelimit-limit` = "60", `x-ratelimit-remaining` = "30", 
        `x-ratelimit-reset` = "1674680415", `x-ratelimit-used` = "30", 
        `x-ratelimit-resource` = "core", `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
        `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
        `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `content-security-policy` = "default-src 'none'", vary = "Accept-Encoding, Accept, X-Requested-With", 
        `x-github-request-id` = "B2FA:1776:933161:95B562:63D19327"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(server = "GitHub.com", date = "Wed, 25 Jan 2023 20:37:59 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `content-length` = "90", `x-github-media-type` = "github.v3", 
            `x-ratelimit-limit` = "60", `x-ratelimit-remaining` = "30", 
            `x-ratelimit-reset` = "1674680415", `x-ratelimit-used` = "30", 
            `x-ratelimit-resource` = "core", `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
            `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
            `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
            `content-security-policy` = "default-src 'none'", 
            vary = "Accept-Encoding, Accept, X-Requested-With", 
            `x-github-request-id` = "B2FA:1776:933161:95B562:63D19327"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"message\": \"Bad credentials\",\n  \"documentation_url\": \"https://docs.github.com/rest\"\n}\n"), 
    date = structure(1674679079, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 3e-05, pretransfer = 6.5e-05, starttransfer = 0.155567, 
    total = 0.155588)), class = "response")
